FROM postgres:12
MAINTAINER Mike Dillon <mike@appropriate.io>

ENV POSTGIS_MAJOR 3
#ENV POSTGIS_VERSION 2.5.3+dfsg-1~exp1.pgdg100+1
#ENV POSTGIS_VERSION 3.0.0~alpha4+dfsg-2~exp1.pgdg100+1
#ENV POSTGIS_VERSION 3.0.0~rc1+dfsg-1~exp2~220.git765f6ff.pgdg100+1
ENV POSTGIS_VERSION 3.0.0+dfsg-2~exp1.pgdg100+1 


RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg-testing main" >> /etc/apt/sources.list.d/pgdg.list \
      && apt-get update \
      && apt-cache showpkg postgis-$POSTGIS_MAJOR \
      && apt-get install -y --no-install-recommends \
			postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
			postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts=$POSTGIS_VERSION \ 
			postgis=$POSTGIS_VERSION \
      && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./conf/postgresql.conf /var/lib/postgresql/data/
ADD ./scripts/postgis.sh /docker-entrypoint-initdb.d
ADD ./scripts/update-postgis.sh /usr/local/bin

ADD ./scripts/tune-postgis.sh /docker-entrypoint-initdb.d
