version: '3.5'
services:
  kosmtik:
    image: kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/openstreetmap-carto
    depends_on:
      - db
    ports:
#      - "127.0.0.1:6789:6789"
      - "6789:6789"
    environment:
      - PGHOST=db
      - PGUSER=postgres
  db:
    image: db:v1
    build:
      context: .
      dockerfile: Dockerfile.db
      shm_size: '10g'
    shm_size: '10g'
    volumes:
#      - ../openstreetmap-data:/openstreetmap-carto
      - ../openstreetmap-data/postgres:/var/lib/postgresql
      - ../openstreetmap-fonts:/usr/local/share/fonts
    ports:
      - "127.0.0.1:6432:5432"
    environment:
      - PG_WORK_MEM=100MB
      - PG_MAINTENANCE_WORK_MEM=10GB
  import:
    image: import:v1
    build:
      context: .
      dockerfile: Dockerfile.import
      shm_size: '10g'
    shm_size: '10g'
    volumes:
      - .:/openstreetmap-carto
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM=4000MB
      - PG_MAINTENANCE_WORK_MEM=10GB
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC=10
      - OSM2PGSQL_DATAFILE
